openapi: 3.0.1
info:
  title: 3d ingestion catalog
  description: Service to create 3d ingestion catalog
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:8085
paths:
  /metadata:
    get:
      operationId: getAll
      summary: Get all 3d models metadata records
      tags:
        - metadata
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/records'
        204:
          description: OK
        '5XX':
          $ref: '#/components/responses/unexpectedError'
    post:
      operationId: createRecord
      summary: Create a new 3d model metadata record
      tags:
        - metadata
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/record'
      responses:
        201:
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/record'
        400:
          $ref: '#/components/responses/badRequest'
        '5XX':
          $ref: '#/components/responses/unexpectedError'
components:
  responses:
    badRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    unexpectedError:
      description: Unexpected Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    records:
      type: array
      items:
        $ref: '#/components/schemas/record'
    record:
      type: object
      description: 3d tiles metadata record
      required:
        - identifier
        - typeName
        - schema
        - mdsource
        - xml
        - anytext
        - insertDate
      properties:
        identifier:
          type: string
          description: Product's unique identifier
        typeName:
          type: string
          description: Product name
        schema:
          type: string
          description: Schema
        mdsource:
          type: string
          description: MD source
        xml:
          type: string
          description: XML
        anytext:
          type: string
          description: Anytext
        insertDate:
          type: string
          format: date-time
          description: Insertion date
        creationDate:
          type: string
          format: date-time
          description: Creation date
        validationDate:
          type: string
          format: date-time
          description: Validation date
        wktGeometry:
          type: string
          description: Well-Known-Text geometry
        title:
          type: string
          description: Title
        producerName:
          type: string
          description: The organization that produced/supplied the product
          enum:
            - IDFMU
          default: IDFMU
        description:
          type: string
          description: Description
        type:
          type: string
          description: Type
        classification:
          type: string
          description: Product classification
        srs:
          type: string
          description: The product reference system, including a vertical data
        projectName:
          type: string
          description: Project name
        version:
          type: string
          description: Version
        centroid:
          type: string
          description: Centroid
        footprint:
          type: string
          description: Footprint
        timeBegin:
          type: string
          format: date-time
          description: Begining time
        timeEnd:
          type: string
          format: date-time
          description: Ending time
        sensorType:
          type: string
          description: The sensor used as the source of the product
        region:
          type: string
          description: Region
        nominalResolution:
          type: string
          description: Nominal resolution
        accuracyLE90:
          type: string
          description: LE90 of the height values
        horizontalAccuracyCE90:
          type: string
          description: CE90 of location of elevation points
        relativeAccuracyLE90:
          type: string
          description: LE90 of distance measurement
        estimatedPrecision:
          type: string
          description: Estimated precision
        measuredPrecision:
          type: string
          description: Measured precision
        links:
          type: string
          description: Links
        anytextTsvector:
          type: string
          description: Anytext tsvector
        wkbGeometry:
          type: string
          description: WKB geometry
