{{- $chartName := include "catalog.name" . -}}
{{- $tracingUrl := include "catalog.tracingUrl" . -}}
{{- $configmapName := include "configmap.fullname" . }}
{{- $metricsUrl := include "catalog.metricsUrl" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmapName }}
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  {{- $postgres := (include "common.postgres.merged" . ) | fromYaml }}
  DB_HOST: {{ quote $postgres.host }}
  DB_PORT: {{ quote $postgres.port }}
  DB_NAME: {{ $postgres.name }}
  DB_CERT_PATH: /tmp/certs/{{ $postgres.ssl.certFileName }}
  DB_KEY_PATH: /tmp/certs/{{ $postgres.ssl.keyFileName }}
  DB_CA_PATH: /tmp/certs/{{ $postgres.ssl.caFileName }}
  DB_ENABLE_SSL_AUTH: {{ $postgres.ssl.enabled | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  TELEMETRY_METRICS_BUCKETS: {{ .Values.env.metrics.buckets | toJson | quote }}
  {{ end }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
