{{- $releaseName := .Release.Name -}}
{{- $chartName := include "catalog.name" . -}}
{{- $cloudProviderFlavor := include "catalog.cloudProviderFlavor" . -}}
{{- $tag := include "catalog.tag" . -}}
{{- $cloudProviderImagePullSecretName := include "catalog.cloudProviderImagePullSecretName" . -}}
{{- $cloudProviderDockerRegistryUrl := include "catalog.cloudProviderDockerRegistryUrl" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "catalog.environment" . }}
    release: {{ $releaseName }}
    {{- include "catalog.labels" . | nindent 4 }}
{{- $splunk := (include "common.splunk.merged" . ) | fromYaml }}   
{{- if $splunk.enabled }}
{{- with $splunk.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-{{ $chartName }}
      {{- include "catalog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-{{ $chartName }}
        {{- include "catalog.selectorLabels" . | nindent 8 }}
    spec:
      {{- if $cloudProviderImagePullSecretName }}
      imagePullSecrets:
        - name: {{ $cloudProviderImagePullSecretName | quote }}
      {{- end }}
      containers:
        - name: {{ $releaseName }}-{{ $chartName }}-deployment
          {{- with .Values.image }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ $tag }}
          {{- end }}
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                {{- $postgres := (include "common.postgres.merged" . ) | fromYaml }}
                  name: {{ $postgres.user.secretName }}
                  key: username
            {{- if $postgres.user.requirePassword }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $postgres.user.secretName }}
                  key: password
            {{- end }}
            - name: SERVER_PORT
              value: {{ .Values.env.targetPort | quote }}
          envFrom:
            - configMapRef:
                name: {{ $releaseName }}-{{ $chartName }}-configmap
            - configMapRef:
                name: {{ .Release.Name }}-{{ $chartName }}-configmap
          ports:
            - name: http
              containerPort: {{ .Values.env.targetPort }}
              protocol: {{ .Values.env.protocol }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /liveness
              port: http
            timeoutSeconds: 20
            periodSeconds: 30
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}
          {{- $postgres := (include "common.postgres.merged" . ) | fromYaml }}          
          {{- if $postgres.ssl.enabled }}
          volumeMounts:
            {{- if $postgres.ssl.enabled }}
            - name: cert-conf
              mountPath: /tmp/certs
              readOnly: true
            {{- end }}
          {{- end }}
      {{- if $postgres.ssl.enabled }}
      volumes:
        {{- if $postgres.ssl.enabled }}
        - name: cert-conf
          secret:
            secretName: {{ $postgres.ssl.secretName }}
        {{- end }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      {{- if .Values.sidecars }}
      {{ tpl (.Values.sidecars) . | nindent 8 }} 
      {{- end }}
      