apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      podName: 3d-ingestion-catalog-pod 
  template:
    metadata:
      labels:
        podName: 3d-ingestion-catalog-pod
    spec:
      containers:
      - name: 3d-ingestion-catalog
        env:
        - name: SERVER_PORT
          value: {{ .Values.metadata.port | quote }}
        image: {{ .Values.metadata.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.metadata.port }}
