{{- $releaseName := .Release.Name -}}
{{- $chartName := include "3d-ingestion-catalog.name" . -}}
{{- if (not .Values.db.useExternal) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secretName }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "3d-ingestion-catalog.environment" . }}
    release: {{ $releaseName }}
    {{- include "3d-ingestion-catalog.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.db.username | b64enc }}
  {{- if .Values.db.requirePassword }}
  password: {{ .Values.db.password | b64enc }}
  {{- end }}
{{- end }}
