{{- $releaseName := .Release.Name -}}
{{- $chartName := include "catalog.name" . -}}
{{- if not .Values.global.postgres.user.useExternal -}}
apiVersion: v1
kind: Secret
metadata:
  {{-  $postgres := (include "common.postgres.merged" . ) | fromYaml }}
  name: {{ $postgres.user.secretName }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "catalog.environment" . }}
    release: {{ $releaseName }}
    {{- include "catalog.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ $postgres.user.username | b64enc }}
  {{- if $postgres.user.requirePassword }}
  password: {{ $postgres.user.password | b64enc }}
  {{- end }}
{{- end }}
