{{- $releaseName := .Release.Name -}}
{{- $chartName := include "3d-ingestion-catalog.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-secret
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "3d-ingestion-catalog.environment" . }}
    release: {{ $releaseName }}
    {{- include "3d-ingestion-catalog.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.dbConfig.username | b64enc }}
  DB_PASSWORD: {{ .Values.dbConfig.password | b64enc }}
{{- end }}
