{{- $releaseName := .Release.Name -}}
{{- $chartName := include "catalog.name" . -}}
{{- $cloudProviderFlavor := include "catalog.cloudProviderFlavor" . -}}
{{- $serviceName := include "catalog.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "catalog.environment" . }}
    release: {{ $releaseName }}
    {{- include "catalog.labels" . | nindent 4 }}
spec:
  {{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: {{ .Values.env.protocol }}
      name: http
      {{- if eq $cloudProviderFlavor "minikube" }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $releaseName }}-{{ $chartName }}
    {{- include "catalog.selectorLabels" . | nindent 4 }}
