apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    podName: 3d-ingestion-catalog-pod
  ports:
  - protocol: TCP
    port: 8080
    targetPort: {{ .Values.metadata.port }}
    name: http
