{
 "title": "Catalog",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Service State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{service_name=\"3d-catalog\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total{service_name=\"3d-catalog\"}[3m])*1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total POST Requests",
   "type": "stat",
   "description": "Represents request for creating a new model",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{service_name=\"3d-catalog\", method=\"POST\"})",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "http_request_duration_seconds_count{service_name=\"3d-catalog\", method=\"POST\"}",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Total PATCH Requests",
   "type": "stat",
   "description": "Represents update metadata of a model",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{service_name=\"3d-catalog\", method=\"PATCH\"})",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "http_request_duration_seconds_count{service_name=\"3d-catalog\", method=\"PATCH\"}",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service_name=\"3d-catalog\"}[2m])) by(method)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}