global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}
image:
  repository: 3d-ingestion-catalog
  tag: v4.1.1
enabled: true
environment: development
initialDelaySeconds: 60
nodePort: 30030
replicaCount: 1
cloudProvider:
  dockerRegistryUrl: acrarolibotnonprod.azurecr.io
  flavor: openshift
env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: 'http://localhost:55681/v1/trace'
  metrics:
    enabled: false
    url: 'http://localhost:55681/v1/metrics'
resources:
  enabled: true
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
db:
  host: 10.0.4.4
  port: 5432
  username: postgres
  password: Libot4allnonprod
  database: 3d-catalog-manager-dev
  requirePassword: true
  sslEnable: false
  useExternal: true
  secretName: catalog-3d-dev-secret
  certFileName: certFile
  keyFileName: keyFile
  caFileName: caFile
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/mergeable-ingress-type: minion
    nginx.org/rewrites: >-
      serviceName={{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 |
      trimSuffix "-" }} rewrite=/
    path: /3d-ingestion-catalog/
route:
  enabled: true
ca:
  enable: false
  useExternal: true
  externalSecretName: 'root.ca'
  secretName: 'root.ca'
  path: '/usr/local/share/ca-certificates'
  key: 'ca.crt'

annotations:
  collectord.io/index: SPLUNK_INDEX
  collectord.io/logs-output: splunk
  collectord.io/procstats-output: devnull
  collectord.io/netstats-output: devnull
  collectord.io/nettable-output: devnull
  collectord.io/stats-output: devnull
logsFilebeat:
  enabled: true
  filebeatImage: docker.elastic.co/beats/filebeat:7.12.1
  mountPath: /usr/src/app/logs