name: tests

on: [pull_request]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    container: node:12

    services:
      # Label used to access the service container
      db:
        # Docker Hub image
        image: postgres:12
        # Provide the user and password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: 3d-catalog-manager-dev
        # Provide the port for postgres
        ports:
          - 6432:6432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_HOST: 10.8.1.20
      DB_NAME: 3d-catalog-manager-dev

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js dependencies
        run: npm ci

      - name: Create table
        run: npm run migration:run

      - name: Run tests
        run: npm run test

      - uses: actions/upload-artifact@v2
        with:
          name: Test Reporters
          path: reports/**
