name: tests

on: [pull_request]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      db:
        # Docker Hub image
        image: postgres:13
        # Provide the user and password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: catalog
        # Provide the port for postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_HOST: db
      DB_NAME: catalog

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: npm ci

      # - name: Create table
      #   run: npm run migration:run

      - name: Run tests
        run: npm run test:unit

      - uses: actions/upload-artifact@v2
        with:
          name: Test Reporters
          path: reports/**
